apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: icoolguypipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: icoolguypipelinesjavascriptdocker 
    spec:
      containers:
        - name: icoolguypipelinesjavascriptdocker 
          image: lohittestregistry.azurecr.io/icoolguypipelinesjavascriptdocker
          ports:
          - containerPort: 8080